#Relative minimum support (%)
#relativeMinSup=n that means n% of the sequences
relativeMinSup=1

#discoveryMode=init
discoveryMode=discovery

#Data
datasetName=freqEpisodes

sequencesInputFile=C:\\Users\\nuhad\\Downloads\\Data\\sequences\\event-seq-2.csv
eventNameSetsOutputFile=C:\\temp\\fSeq2\\eTypes2
freqEventNamesInputFile=C:\\temp\\fSeq2\\eTypes2FreqItems
freqEventNameSetsInputDir=C:\\temp\\fSeq2\\
freqEpisodesOutputDir=C:\\temp\\outFSeq2

outputFilePerFreqEvent=yes

#CSV
delimiter=|
quote="
escape=\\
skipHeader=yes
#skipHeader=no



