#Relative minimum support (%)
#relativeMinSup=n that means n% of the records
relativeMinSup=1

#Data
datasetName=eTypes3
inputDataFile=C:\\temp\\fSeq2\\eTypes3
outputDataDir=C:\\temp\\fSeq2
#outputFilePerFrequentItem=no
outputFilePerFrequentItem=yes

#CSV
delimiter=,
quote="
escape=\\
skipHeader=yes
#skipHeader=no
